### ISSUE TITLE
website API

### ISSUE THREAD

**Issue by lfoppiano** [TWMC/Website#1]
Hey guys, 
  I was wondering if for the migration of the content from the old website we could use an API to create new pages. If that is possible we could automate the first import of the pages and then review them manually. 

What do you think?

**Comment by nishad** [comment]
@lfoppiano could you elaborate on the API concept?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lfoppiano** [comment]
Basically I'm looking for ways to avoid manually copy-paste the club activities information manually.. Eventually they might need to be manually reviewed but that's less work. 

Rouhgly... I have in mind something like  

`POST /activities/2001`

and I pass a JSON containing some of the field of the page
```json
{
 "name": 
 "location":
 "report":
 "description": 
}
```

and that will create a new page under `/activities/2001`

If needs to be implemented then let's forget about it, cause it's just for migrating the old content to the new website. 

Thanks

**Comment by nishad** [comment]
Super, 

I will look into it.

However, the site uses static files as sources[1]. I assume it is much easier to generate the static files programmatically than going through an API.

[1] https://github.com/TWMC/content/tree/master/2-activities/2015/otama-trail

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lfoppiano** [comment]
I see. Let's forget about the API. I'll look into how to convert the static pages (or some cut and paste of them) into the static file... 👍

**Comment by lfoppiano** [comment]
@nishad one more thing, would be possible to update the github code with the latest version of the website?

**Comment by nishad** [comment]
@lfoppiano creating static files for Kirby is simple than automating a restful API. If you are interested, see this [1], you can find some gold in there. 

TWMC website’s git based workflow is obsolete; let me see if I can bring it back. 

[1] https://github.com/bcorporaal/kirby-python-scripts

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
