### ISSUE TITLE
Google maps seems having problems 

### ISSUE THREAD

**Issue by lfoppiano** [TWMC/Website#12]
I've been reported a problem with the map in the activity page. It seems that the connection to the Google API has some issues. This what happens when the page is loaded: 

<img width="877" alt="Screenshot 2019-10-31 at 07 11 27" src="https://user-images.githubusercontent.com/15426/67903023-e61bb400-fbad-11e9-860c-045f6d7f701e.png">

When you search for a location you get: 
<img width="459" alt="image" src="https://user-images.githubusercontent.com/15426/67903104-1fecba80-fbae-11e9-993e-4c4932eb9e58.png">

**Comment by nishad** [comment]
Fixed, Issues with google geocoding API billing glitch [1] with one of the API accesses used for TWMC.

[1] https://developers.google.com/maps/faq#gmp_restricted_regions

**Comment by lfoppiano** [comment]
Thank you for the quick fix! 😄
