### ISSUE TITLE
Update github workflow

### ISSUE THREAD

**Issue by lfoppiano** [TWMC/Website#3]
I think I have written some python scripts that converts the previous walks  pages into kirby files... The old HTML style (no ids) was quite paninful to parse properly. 

I'd like to test it on the full set of previuos walk pages before. And as we discussed in the other issue #1 , to get the github updated so I can test. 

I open a new issue so they are separated

**Comment by nishad** [comment]
GitHub based workflow is back.

* All push to content repository will be updated to the main site in a couple of seconds.
* Changes from the website panel will be synced to the repository in every 30 minutes.
* There are new options in the Dashboard to sync content manually.
* Conflict resolution is a bit tricky in an automated workflow, be sensible while editing the same file through git and dashboard simultaneously. It may create unnecessary conflicts and as a result, the content may go out of sync. In such scenarios please sync the content manually though the dashboard before you push to the changes to GitHub.

**Comment by lfoppiano** [comment]
Thanks!
